# 记录一些常量
# 以下是设备的
WAITING_AREA_CAPACITY = 6
QUICK_CHARGE_NUMBER = 2
SLOW_CHARGE_NUMBER = 3
QUICK_CHARGE_POWER = 30
SLOW_CHARGE_POWER = 7
NUMBER_OF_CHARGE_PILE = 2

# 用户名和密码长度
NAME_AND_PASSWORD_LEN = 20
